---

# Installation tasks
- name: 'INSTALL | APT | Import aptly GPG key'
  apt_key:
    id: "{{ aptly_gpg_key }}"
    keyserver: "{{ aptly_gpg_keyserver }}"
    state: 'present'


- name: 'INSTALL | APT | Manage aptly repository'
  apt_repository:
    repo: "{{ aptly_repository }}"
    update_cache: True
    state: 'present'
    mode: "{{ aptly_repository_file_mode }}"


- name: 'INSTALL | GROUP | Ensure aptly group'
  group:
    name: "{{ aptly_group }}"
    gid: "{{ aptly_gid | default(omit) }}"


- name: 'INSTALL | USER | Ensure aptly user'
  user:
    name: "{{ aptly_user }}"
    comment: 'User for aptly repository management'
    home: "{{ aptly_user_home }}"
    group: "{{ aptly_group }}"
    shell: '/bin/bash'
    uid: "{{ aptly_uid | default(omit) }}"


- name: 'INSTALL | USER | Change home permission'
  file:
    dest: "{{ aptly_user_home }}"
    mode: "{{ aptly_user_home_mode }}"


- name: 'INSTALL | APT | Install aptly package'
  apt:
    name: 'aptly={{ aptly_version }}'
    cache_valid_time: 3600
    update_cache: True

- name: 'INSTALL | APT | Install aptly package'
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ aptly_keyring_packages }}'
