---

# Main tasks file for aptly

- name: 'INSTALL | Include installation tasks'
  include: "{{ role_path }}/tasks/installation.yml"
  tags:
    - 'role::aptly'
    - 'role::aptly::install'


- name: 'GPG | Include custom GPG key management tasks'
  include: "{{ role_path }}/tasks/custom_gpg_key.yml"
  become_user: '{{ aptly_user }}'
  tags:
    - 'role::aptly'
    - 'role::aptly::custom-gpg'


- name: 'CONFIG | Include configuration management tasks'
  include: "{{ role_path }}/tasks/configuration.yml"
  become_user: '{{ aptly_user }}'
  tags:
    - 'role::aptly'
    - 'role::aptly::config'
